{
 "title": "Overview",
 "tags": [
  "pytest",
  "observability",
  "otel"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Last 10 PRs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, max by (pr) ((last_over_time(pytest_run_end_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) * 1000))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (pr, title) (topk(1, last_over_time(pytest_pr_info{pr=~\".*\",pr!=\"main\",title!=\"\"}[$__range])) by (pr))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (pr) (max by (pr, run_id) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pr) (max by (pr, run_id) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_failed_tests{pr=~\".*\",pr!=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_failed_tests{pr=~\".*\",pr!=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) and on (pr, run_id) (max by (pr, run_id) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) == on (pr) group_left() max by (pr) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range])))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * sum by (pr) (max by (pr, run_id) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_failed_tests{pr=~\".*\",pr!=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_failed_tests{pr=~\".*\",pr!=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) and on (pr, run_id) (max by (pr, run_id) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) == on (pr) group_left() max by (pr) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))))) / sum by (pr) (max by (pr, run_id) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_total_tests{pr=~\".*\",pr!=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_total_tests{pr=~\".*\",pr!=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) and on (pr, run_id) (max by (pr, run_id) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range]))) == on (pr) group_left() max by (pr) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\",pr!=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\",pr!=\"main\"}[$__range])))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor((time() - max by (pr) (last_over_time(pytest_pr_created_at_seconds{pr=~\".*\",pr!=\"main\"}[$__range]))) / 86400)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (pr) (last_over_time(pytest_pr_state{pr=~\".*\",pr!=\"main\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Main Branch - Last 10 Runs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, max by (run_id, pr) (last_over_time(pytest_run_start_time_seconds{pr=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range])))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (run_id, pr) (last_over_time(pytest_run_job_member_info{pr=\"main\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (run_id, pr) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_total_tests{pr=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_total_tests{pr=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (run_id, pr, commit_message, html_url) (last_over_time(pytest_run_info{pr=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (run_id, pr) (last_over_time(pytest_run_duration_seconds{pr=\"main\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * max by (run_id, pr) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_failed_tests{pr=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_failed_tests{pr=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range]))) / max by (run_id, pr) ((sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_total_tests{pr=\"main\"}[$__range])) or sum by (service_name, provider, pr, run_id) (last_over_time(pytest_run_total_tests{pr=\"main\"}[$__range]))) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=\"main\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 10 Runs",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10, max by (run_id, pr) (last_over_time(pytest_run_start_time_seconds{pr=~\".*\"}[$__range]) * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (last_over_time(pytest_run_job_member_info{test_job=~\".*\",pr=~\".*\"}[$__range])))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (run_id, pr) (last_over_time(pytest_run_job_member_info{pr=~\".*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Failing Tests (main branch)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "legendFormat": "__auto",
     "expr": "topk(10, count by (test_job, test_class, test_function, test_module) (last_over_time(pytest_test_duration_seconds{pr=\"main\",status_code=\"ERROR\"}[$__range]))) * on (test_job, test_class, test_function, test_module) group_left(exception_type, trace_id) ((topk by (test_job, test_class, test_function, test_module) (1, timestamp(last_over_time(pytest_test_last_failure_info{pr=\"main\"}[$__range])))) >= bool 0)"
    }
   ]
  },
  {
   "title": "Slowest Tests By Average Duration (main branch)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "__auto",
     "expr": "sort_desc(topk(20, avg by (test_job, test_module, test_class, test_function) (last_over_time(pytest_test_duration_seconds{pr=\"main\"}[$__range]))))"
    }
   ]
  }
 ]
}