{
 "title": "Pytest Observability - Suite",
 "tags": [
  "pytest",
  "observability",
  "otel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(pytest_test_average_duration_seconds, service_name)"
    }
   },
   {
    "name": "suite",
    "label": "Suite",
    "query": {
     "query": "label_values(pytest_test_average_duration_seconds{service_name=~\"$service\"}, test_suite)"
    }
   },
   {
    "name": "pr",
    "label": "PR",
    "query": {
     "query": "label_values(pytest_test_average_duration_seconds{service_name=~\"$service\",test_suite=~\"$suite\"}, pr)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(pytest_test_failure_count{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"}) / sum(pytest_test_run_count{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 10 Runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, (pytest_run_start_time_seconds{service_name=~\"$service\",pr=~\"$pr\"} * on (service_name, provider, pr, run_id) group_left() max by (service_name, provider, pr, run_id) (pytest_run_suite_member_info{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"})) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Failing Tests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, (pytest_test_failure_count{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"} > 0) * on(test_nodeid, test_suite, service_name, provider, pr) group_left(trace_id, exception_type) last_over_time(pytest_test_last_failure_info{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slowest Tests By Average Duration",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk(20, pytest_test_average_duration_seconds{service_name=~\"$service\",test_suite=~\"$suite\",pr=~\"$pr\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}